#pragma once
#include <alaio/vm/opcodes_def.hpp>
#include <alaio/vm/variant.hpp>

#include <map>

namespace alaio { namespace vm {
   enum opcodes {
      ALA_VM_CONTROL_FLOW_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_BR_TABLE_OP(ALA_VM_CREATE_ENUM)
      ALA_VM_RETURN_OP(ALA_VM_CREATE_ENUM)
      ALA_VM_CALL_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_CALL_IMM_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_PARAMETRIC_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_VARIABLE_ACCESS_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_MEMORY_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_I32_CONSTANT_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_I64_CONSTANT_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_F32_CONSTANT_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_F64_CONSTANT_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_COMPARISON_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_NUMERIC_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_CONVERSION_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_EXIT_OP(ALA_VM_CREATE_ENUM)
      ALA_VM_EMPTY_OPS(ALA_VM_CREATE_ENUM)
      ALA_VM_ERROR_OPS(ALA_VM_CREATE_ENUM)
   };

   struct opcode_utils {
      std::map<uint16_t, std::string> opcode_map{
         ALA_VM_CONTROL_FLOW_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_BR_TABLE_OP(ALA_VM_CREATE_MAP)
         ALA_VM_RETURN_OP(ALA_VM_CREATE_MAP)
         ALA_VM_CALL_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_CALL_IMM_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_PARAMETRIC_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_VARIABLE_ACCESS_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_MEMORY_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_I32_CONSTANT_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_I64_CONSTANT_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_F32_CONSTANT_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_F64_CONSTANT_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_COMPARISON_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_NUMERIC_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_CONVERSION_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_EXIT_OP(ALA_VM_CREATE_MAP)
         ALA_VM_EMPTY_OPS(ALA_VM_CREATE_MAP)
         ALA_VM_ERROR_OPS(ALA_VM_CREATE_MAP)
      };
   };

   enum imm_types {
      none,
      block_imm,
      varuint32_imm,
      br_table_imm,
   };


   ALA_VM_CONTROL_FLOW_OPS(ALA_VM_CREATE_CONTROL_FLOW_TYPES)
   ALA_VM_BR_TABLE_OP(ALA_VM_CREATE_BR_TABLE_TYPE)
   ALA_VM_RETURN_OP(ALA_VM_CREATE_CONTROL_FLOW_TYPES)
   ALA_VM_CALL_OPS(ALA_VM_CREATE_CALL_TYPES)
   ALA_VM_CALL_IMM_OPS(ALA_VM_CREATE_CALL_IMM_TYPES)
   ALA_VM_PARAMETRIC_OPS(ALA_VM_CREATE_TYPES)
   ALA_VM_VARIABLE_ACCESS_OPS(ALA_VM_CREATE_VARIABLE_ACCESS_TYPES)
   ALA_VM_MEMORY_OPS(ALA_VM_CREATE_MEMORY_TYPES)
   ALA_VM_I32_CONSTANT_OPS(ALA_VM_CREATE_I32_CONSTANT_TYPE)
   ALA_VM_I64_CONSTANT_OPS(ALA_VM_CREATE_I64_CONSTANT_TYPE)
   ALA_VM_F32_CONSTANT_OPS(ALA_VM_CREATE_F32_CONSTANT_TYPE)
   ALA_VM_F64_CONSTANT_OPS(ALA_VM_CREATE_F64_CONSTANT_TYPE)
   ALA_VM_COMPARISON_OPS(ALA_VM_CREATE_TYPES)
   ALA_VM_NUMERIC_OPS(ALA_VM_CREATE_TYPES)
   ALA_VM_CONVERSION_OPS(ALA_VM_CREATE_TYPES)
   ALA_VM_EXIT_OP(ALA_VM_CREATE_EXIT_TYPE)
   ALA_VM_EMPTY_OPS(ALA_VM_CREATE_TYPES)
   ALA_VM_ERROR_OPS(ALA_VM_CREATE_TYPES)

   using opcode = variant<
      ALA_VM_CONTROL_FLOW_OPS(ALA_VM_IDENTITY)
      ALA_VM_BR_TABLE_OP(ALA_VM_IDENTITY)
      ALA_VM_RETURN_OP(ALA_VM_IDENTITY)
      ALA_VM_CALL_OPS(ALA_VM_IDENTITY)
      ALA_VM_CALL_IMM_OPS(ALA_VM_IDENTITY)
      ALA_VM_PARAMETRIC_OPS(ALA_VM_IDENTITY)
      ALA_VM_VARIABLE_ACCESS_OPS(ALA_VM_IDENTITY)
      ALA_VM_MEMORY_OPS(ALA_VM_IDENTITY)
      ALA_VM_I32_CONSTANT_OPS(ALA_VM_IDENTITY)
      ALA_VM_I64_CONSTANT_OPS(ALA_VM_IDENTITY)
      ALA_VM_F32_CONSTANT_OPS(ALA_VM_IDENTITY)
      ALA_VM_F64_CONSTANT_OPS(ALA_VM_IDENTITY)
      ALA_VM_COMPARISON_OPS(ALA_VM_IDENTITY)
      ALA_VM_NUMERIC_OPS(ALA_VM_IDENTITY)
      ALA_VM_CONVERSION_OPS(ALA_VM_IDENTITY)
      ALA_VM_EXIT_OP(ALA_VM_IDENTITY)
      ALA_VM_EMPTY_OPS(ALA_VM_IDENTITY)
      ALA_VM_ERROR_OPS(ALA_VM_IDENTITY_END)
      >;
}} // namespace alaio::vm
